# Generated by Django 5.0.2 on 2024-02-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
